controller_list:
  - name: left_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - L_hip_joint
      - L_hip2_joint
      - L_thigh_joint
      - L_calf_joint
      - L_toe_joint
  - name: right_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - R_hip_joint
      - R_hip2_joint
      - R_thigh_joint
      - R_calf_joint
      - R_toe_joint